"""Render PriMock57 transcripts as synthetic speech, and measure what the acoustics cost.

The bet this tests: the organisers will not hand us recorded consultations,
because no such corpus exists to hand out. Five editions of their data comes
from public academic sets, simulators, or LLM generation, the 2025 healthcare
task says outright that its statements were "generated by Claude Opus", and they
archived a voice-cloning TTS engine seventeen days before this event. So the
evaluation audio is probably synthesised.

If it is, our 13.9% WER is the wrong number to plan against, and this script
finds the right one. Same words, same references, same scorer. Only the
acoustics change, which is what makes the difference attributable.

Three conditions, and the middle one is the point:

    real         the original two-microphone recording, mixed down. 13.9%.
    tts-timed    synthetic voices placed at the ORIGINAL timestamps, so every
                 pause, every interruption and every overlap is preserved
    tts-seq      synthetic voices concatenated one after another with a fixed
                 gap. No overlap at all.

real minus tts-timed is what recording quality costs: microphones, room, bleed.
tts-timed minus tts-seq is what conversational overlap costs. Collapsing both
into one number tells you nothing about which to attack.

    python scripts/tts_render.py --n 6
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import io
import json
import sys
import time
from pathlib import Path

import numpy as np
import soundfile as sf
from scipy.signal import resample_poly

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from medvoice.dataset import load, split  # noqa: E402
from medvoice.metrics import corpus_wer, term_recall  # noqa: E402

SR = 16000

# One voice per role, and they must be clearly distinct. If the organisers used
# voice cloning, their speakers will differ far more than two stock voices do,
# so a same-gender pair here would flatter any diarization we build later.
VOICES = {"Doctor": "en-GB-RyanNeural", "Patient": "en-GB-SoniaNeural"}
VOICES_DA = {"Doctor": "da-DK-JeppeNeural", "Patient": "da-DK-ChristelNeural"}


class _Translated:
    """An Utterance with its text replaced, keeping the original timing."""

    __slots__ = ("speaker", "start", "end", "_text")

    def __init__(self, u, text: str):
        self.speaker, self.start, self.end, self._text = u.speaker, u.start, u.end, text

    def clean(self, *a, **k) -> str:
        return self._text


def translator():
    """en->da machine translation, 75 MB, runs on CPU in seconds per utterance."""
    from transformers import MarianMTModel, MarianTokenizer

    name = "Helsinki-NLP/opus-mt-en-da"
    tok = MarianTokenizer.from_pretrained(name)
    mt = MarianMTModel.from_pretrained(name).eval()
    memo: dict[str, str] = {}

    def go(text: str) -> str:
        if text not in memo:
            import torch
            b = tok([text], return_tensors="pt", truncation=True, max_length=512)
            with torch.inference_mode():
                y = mt.generate(**b, max_new_tokens=512, num_beams=1)
            memo[text] = tok.decode(y[0], skip_special_tokens=True)
        return memo[text]

    return go


async def _say(text: str, voice: str, cache: Path) -> np.ndarray:
    """Synthesise one utterance, cached on disk by (text, voice).

    The cache is not an optimisation, it is what makes the experiment
    repeatable: edge-tts is a network service, and without it a rerun a week
    later would be comparing against slightly different audio.
    """
    import edge_tts

    key = hashlib.sha1(f"{voice}|{text}".encode("utf-8")).hexdigest()[:16]
    f = cache / f"{key}.mp3"
    if not (f.is_file() and f.stat().st_size > 512):
        buf = b""
        for attempt in range(3):
            try:
                comm = edge_tts.Communicate(text, voice)
                buf = b""
                async for ch in comm.stream():
                    if ch["type"] == "audio":
                        buf += ch["data"]
                if len(buf) > 512:
                    break
            except Exception:
                await asyncio.sleep(1.5 * (attempt + 1))
        if len(buf) <= 512:
            return np.zeros(0, dtype=np.float32)
        f.write_bytes(buf)

    x, sr = sf.read(io.BytesIO(f.read_bytes()), dtype="float32", always_2d=False)
    if x.ndim > 1:
        x = x.mean(axis=1)
    if sr != SR:                                  # edge-tts returns 24 kHz
        g = np.gcd(int(sr), SR)
        x = resample_poly(x, SR // g, int(sr) // g).astype(np.float32)
    return x


async def render(utterances, voices: dict, mode: str, cache: Path,
                 gap_s: float = 0.25) -> tuple[np.ndarray, dict]:
    cache.mkdir(parents=True, exist_ok=True)
    items = [(u, u.clean()) for u in utterances]
    items = [(u, t) for u, t in items if t.strip()]

    # A consultation is ~200 utterances. Firing all of them at once gets the
    # connection throttled and comes back as empty clips, which then look like
    # ASR deletions rather than like a rendering failure. Cap the concurrency.
    sem = asyncio.Semaphore(8)

    async def one(u, t):
        async with sem:
            return await _say(t, voices.get(u.speaker, next(iter(voices.values()))), cache)

    clips = await asyncio.gather(*[one(u, t) for u, t in items])
    empty = sum(1 for c in clips if not c.size)
    if empty:
        print(f"    warning: {empty} of {len(items)} utterances failed to synthesise")

    if mode == "seq":
        parts, gap = [], np.zeros(int(gap_s * SR), dtype=np.float32)
        for c in clips:
            if c.size:
                parts.append(c)
                parts.append(gap)
        out = np.concatenate(parts) if parts else np.zeros(SR, dtype=np.float32)
        overlap_s = 0.0
    else:
        # place each clip at the timestamp the human actually spoke at
        ends = [u.start + len(c) / SR for (u, _), c in zip(items, clips) if c.size]
        total = int((max(ends, default=1.0) + 1.0) * SR)
        out = np.zeros(total, dtype=np.float32)
        spans = []
        for (u, _), c in zip(items, clips):
            if not c.size:
                continue
            a = int(u.start * SR)
            b = min(total, a + len(c))
            out[a:b] += c[: b - a]
            spans.append((u.start, u.start + len(c) / SR))
        # how much of the result has two people talking at once
        spans.sort()
        overlap_s = sum(max(0.0, min(p[1], q[1]) - q[0])
                        for p, q in zip(spans, spans[1:]))
    peak = float(np.abs(out).max()) or 1.0
    if peak > 1.0:
        out /= peak
    spoken = sum(len(c) / SR for c in clips if c.size)
    return out, {"clips": sum(1 for c in clips if c.size), "utterances": len(items),
                 "spoken_s": round(spoken, 1), "overlap_s": round(overlap_s, 1),
                 "duration_s": round(len(out) / SR, 1)}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=6)
    ap.add_argument("--modes", default="timed,seq")
    ap.add_argument("--model", default="large-v3")
    # Three language conditions, and the distinction between the last two matters.
    # Pointing Danish voices at English text does NOT test Danish audio; it tests
    # heavily accented English, because the words and the reference are still
    # English. That is a real scenario (Danish clinicians working in English) and
    # worth its own row, but it is not the one that would cost us a day.
    ap.add_argument("--lang", default="en", choices=("en", "accent", "da"),
                    help="en: UK voices on English text. accent: Danish voices on English "
                         "text, scored against the English reference, i.e. accented English. "
                         "da: translate the transcript to Danish first, render it, decode as "
                         "Danish and score against the translation.")
    ap.add_argument("--out", default="runs/tts_delta.json")
    args = ap.parse_args()

    from medvoice.asr import get_model, transcribe

    voices = VOICES if args.lang == "en" else VOICES_DA
    work = Path("work") / f"tts_{args.lang}"
    cache = work / "clips"
    translate = translator() if args.lang == "da" else None
    asr_lang = "da" if args.lang == "da" else "en"

    cons = load()
    _, dev = split(cons)
    dev = [c for c in dev if len(c.audio) == 2][: args.n]
    terms = json.loads((Path("labels") / "content_terms.json").read_text(encoding="utf-8"))
    content = {w.lower() for k, v in terms.items() if not k.startswith("_") for w in v}

    print(f"{len(dev)} consultations, voices {list(voices.values())}\n")
    model = get_model(args.model)
    rows, out = [], {"model": args.model, "lang": args.lang, "conditions": {}}

    for mode in args.modes.split(","):
        pairs, meta, t0 = [], [], time.perf_counter()
        for c in dev:
            wav = work / f"{c.cid}_{mode}.wav"
            utts, ref = c.utterances, c.reference()
            if translate is not None:
                # The translation becomes BOTH the spoken text and the reference,
                # which is exactly the regime a TTS-generated challenge lives in:
                # the generated text IS the ground truth. Translation errors move
                # both sides together and so cannot inflate the score.
                utts = [_Translated(u, translate(u.clean())) for u in utts if u.clean().strip()]
                ref = " ".join(u.clean() for u in utts)
            if not (wav.is_file() and wav.stat().st_size > 4096):
                wav.parent.mkdir(parents=True, exist_ok=True)
                audio, m = asyncio.run(render(utts, voices, mode, cache))
                sf.write(wav, audio, SR)
            else:
                m = {"cached": True}
            r = transcribe(wav, model, language=asr_lang)
            pairs.append((ref, r.hypothesis))
            m["cid"] = c.cid
            m["real_s"] = round(c.duration, 1)
            meta.append(m)

        wer, counts = corpus_wer(pairs)
        wer_nb, _ = corpus_wer(pairs, drop_backchannels=True)
        f = t = 0
        for ref, hyp in pairs:
            a, b = term_recall(ref, hyp, content)
            f += a
            t += b
        row = {"condition": f"tts-{mode}", "wer": round(wer, 4),
               "wer_no_backchannel": round(wer_nb, 4), "sub": counts.subs,
               "del": counts.dels, "ins": counts.ins, "ref_words": counts.ref_len,
               "content_recall": round(f / max(t, 1), 4),
               "render_s": round(time.perf_counter() - t0, 1), "per_file": meta}
        out["conditions"][f"tts-{mode}"] = {k: v for k, v in row.items() if k != "per_file"}
        rows.append(row)

    # the reference point, measured earlier on the same six consultations. Only
    # comparable for lang=en: the other arms are scored against different text.
    real = json.loads(Path("runs/term_recall.json").read_text(encoding="utf-8"))
    if args.lang != "en":
        real = {"wer": float("nan"), "wer_no_backchannel": float("nan"),
                "overall": {"recall": float("nan")}}
    print(f"{'condition':<14}{'WER':>8}{'no-bc':>8}{'sub':>7}{'del':>7}{'ins':>7}{'content':>9}")
    print("-" * 60)
    print(f"{'real (mixed)':<14}{real['wer']:>8.3f}{real['wer_no_backchannel']:>8.3f}"
          f"{'446':>7}{'690':>7}{'213':>7}{real['overall']['recall']:>9.3f}")
    for r in rows:
        print(f"{r['condition']:<14}{r['wer']:>8.3f}{r['wer_no_backchannel']:>8.3f}"
              f"{r['sub']:>7}{r['del']:>7}{r['ins']:>7}{r['content_recall']:>9.3f}")

    d = {r["condition"]: r["wer"] for r in rows}
    if "tts-timed" in d:
        print(f"\nrecording quality costs {real['wer'] - d['tts-timed']:+.3f} WER "
              f"(real minus tts-timed, same overlap structure in both)")
    if "tts-timed" in d and "tts-seq" in d:
        print(f"conversational overlap costs {d['tts-timed'] - d['tts-seq']:+.3f} WER "
              f"(tts-timed minus tts-seq, same voices in both)")
    for r in rows:
        ov = [m.get("overlap_s") for m in r["per_file"] if m.get("overlap_s") is not None]
        if ov:
            print(f"  {r['condition']}: {sum(ov)/len(ov):.0f}s of two-speaker overlap per consultation")

    o = Path(args.out)
    o.parent.mkdir(parents=True, exist_ok=True)
    o.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"\nwrote {o}")


if __name__ == "__main__":
    main()
