// THE OBSERVATION-ONLY BOUNDARY.
//
// This header is the complete and only view the policy translation unit
// (_orchard_policy.cpp -> _orchard.hpp -> _evasion.hpp) has of the outside world.
// That file includes this header, the two policy headers and C++ standard headers,
// and nothing else: no Python.h, no numpy, no _engine.cpp. So it is a compile-time
// fact, not a convention, that the policy cannot reach engine internals, true world
// coordinates, the world seed, fruit/tree ages, predator state or the engine RNG -
// those names simply do not exist in its translation unit, and a reference to one is
// a compilation error.
//
// This replaces the enforcement that models/observation_only.py gets from process
// isolation plus _assert_no_simulator(). See fastsim/check_boundary.py for the
// mechanical check a reviewer can run.
//
// What is declared here, and why each item is allowed:
//   Obs      - one entry of a public observation list. Exactly the fields the
//              simulator publishes: type, distance, angle, rel_dir (Agent/Predator),
//              id (Agent/Fruit), coords (Edge). Nothing else.
//   AState   - one agent's public self-report: agent_id, energy, biome index, age,
//              speed, sprint_speed, hearing_radius, vision_angle, vision_range,
//              max_energy. No x/y, no direction, no engine handle.
//   Act      - what the policy hands back, one ActionRequest.
//   Cfg      - tuning parameters, as a flat (name, value) list.
//   PyRandom / PySetEmu / py_mod / py_hash_* - pure algorithmic reimplementations of
//              CPython semantics (MT19937, set iteration order, float % and //, hash).
//              They carry no simulator state; they exist so the C++ policy reproduces
//              the Python policy's arithmetic and iteration order bit for bit. They
//              are shared with the engine only in the sense of being the same source
//              text (_shared_pysem.inc, sliced out of _engine.cpp by build_policy.py,
//              which fails the build if the slice ever stops matching).
//
// The policy's RNG is seeded from the integer `seed` that the Python
// OrchardEvasionPolicy is constructed with, exactly as in production
// (OrchardPolicy(seed=seed)); it is a policy-private stream and is not the engine's
// RNG state. Removing it would break parity with the Python policy.
#pragma once

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <limits>
#include <memory>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace polabi {

// Generated by build_policy.py from _engine.cpp; the build fails if it drifts.
#include "_shared_pysem.inc"

// The published biome names, as indices. AState::biome is the index of the string the
// observation dict carries in s['biome']; the policy needs RIVER to refuse to breed
// there, exactly as the Python policy's `s['biome'] == 'river'` test does. Asserted
// against the engine's own Biome enum in _policy.cpp.
enum Biome : uint8_t { FOREST = 0, SWAMP = 1, DESERT = 2, GRASSLAND = 3, RIVER = 4 };

// ---------------------------------------------------------------------------
// The transcendental functions, through pointers.
//
// The Python policy calls math.sin/cos/atan2/pow, which on CPython are the C
// runtime's. They are not correctly rounded, so different libms disagree in the last
// bit, and one such bit is enough to change a decision several ticks later. On
// Windows with MinGW this is not hypothetical: g++ -static resolves cos() to
// libmingwex, whose result for cos(2.6639269779272379) is 1 ULP away from
// ucrtbase.dll's, which is what CPython's math.cos returns. That single bit is what
// made the upstream port's own no-predator fixture diverge on this laptop (verified:
// pristine upstream build, upstream verifier, seeds 1/2/3, identical first
// divergences to ours).
//
// So the policy calls through these pointers, and the host installs the same libm
// CPython uses - the direct analogue of what _engine.cpp does with set_numpy_loops
// for the engine's numpy calls. The defaults are the standard library, which is
// already the right answer wherever CPython and the C++ compiler share a libm
// (Linux, macOS). Indirect calls, so no Python and no measurable cost.
//
// Only functions whose rounding is implementation-defined go through here. sqrt,
// fma, fmod, floor, frexp, ldexp and copysign are exact or correctly rounded by
// IEEE-754, so they are called directly.
namespace pm {

inline double (*p_sin)(double) = nullptr;
inline double (*p_cos)(double) = nullptr;
inline double (*p_atan2)(double, double) = nullptr;
inline double (*p_pow)(double, double) = nullptr;

inline double sin(double x) { return p_sin ? p_sin(x) : std::sin(x); }
inline double cos(double x) { return p_cos ? p_cos(x) : std::cos(x); }
inline double atan2(double y, double x) { return p_atan2 ? p_atan2(y, x) : std::atan2(y, x); }
inline double pow(double x, double y) { return p_pow ? p_pow(x, y) : std::pow(x, y); }

// Called once by the host with the CRT that CPython's math module uses.
inline void set_libm(double (*s)(double), double (*c)(double), double (*a)(double, double),
                     double (*pw)(double, double)) {
    p_sin = s; p_cos = c; p_atan2 = a; p_pow = pw;
}

}  // namespace pm

// One published observation. Layout is asserted against the engine's own Obs in
// _policy.cpp so the observation list can be handed over without a copy.
struct Obs {
    // type: 0 Fruit, 1 Agent, 2 Predator, 3 Tree, 4 Edge
    int type;
    double distance, angle, rel_dir;
    bool has_rel_dir;
    int64_t id;
    bool has_id;
    double c[4];  // Edge: the two endpoint offsets ('coords')
};

// One agent's public self-report plus its observation list.
struct AState {
    int64_t aid; const std::vector<Obs>* obs;
    double energy; int biome; double age, speed, sprint, hear, cone, vr, max_energy;
};

struct Act { int64_t aid; double dist, direction, turn; bool spawn; };

// Optional per-phase accounting inside the policy, for answering "where does the
// native policy's time actually go". Off unless the host asks, and never read by a
// decision.
enum Phase { PH_MERGE = 0, PH_OBSERVE, PH_MAINTAIN, PH_ASSIGN, PH_ACT, PH_REST,
             PH_OBS_MARKS, PH_OBS_EDGES, PH_OBS_TREES, PH_OBS_FRUITS,
             PH_MAINTAIN_VIS, PH_MAINTAIN_PRUNE, PH_MAINTAIN_COUNTS, PH_N };
inline const char* const PHASE_NAMES[PH_N] = {"merge", "observe", "maintain", "assign", "act", "rest",
                                             "observe.marks", "observe.edges", "observe.trees",
                                             "observe.fruits", "maintain.visibility",
                                             "maintain.prune", "maintain.counts"};

struct PhaseTimer {
    double* acc;
    bool on;
    std::chrono::steady_clock::time_point t0;
    PhaseTimer(double* a, bool enabled) : acc(a), on(enabled) {
        if (on) t0 = std::chrono::steady_clock::now();
    }
    ~PhaseTimer() {
        if (on) *acc += std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
    }
};

// Tuning config crosses the boundary as a flat name/value list rather than a shared
// struct, so the engine side never needs the policy's parameter layout and the policy
// side never needs a Python dict.
struct CfgItem { const char* key; double value; };
struct Cfg { const CfgItem* items; size_t n; const char* feed_mode; };

}  // namespace polabi
